-- AlterTable
ALTER TABLE "Payment" ALTER COLUMN "at" SET DATA TYPE TIMESTAMPTZ(3),
ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMPTZ(3);

-- AlterTable
ALTER TABLE "Player" ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMPTZ(3);

-- AlterTable
ALTER TABLE "Settings" ALTER COLUMN "roundStartAt" SET DATA TYPE TIMESTAMPTZ(3);

-- AlterTable
ALTER TABLE "Shuttle" ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMPTZ(3);
